### ISSUE TITLE
M14-LAB14: Create a web server Azure VM by using an Ansible playbook not working

### ISSUE THREAD

**Issue by vnvbadri** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#145]
### Contact Details

vamsi.badri@spektrasystems.com

### What happened?

Exercise : 01
Task: 06
Step: 09

Description of issue:

While running this command 

sudo ansible-playbook ~/PartsUnlimitedMRP/Labfiles/AZ-400T05-ImplemntgAppInfra/Labfiles/ansible/new_vm_web.yml --extra-vars "vmname=<VM_name> resgrp=az400m14l03arg vnet=az400m1403aVNET subnet=az400m1403aSubnet"

getting below error

TASK [Create storage account] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error retrieving resource group az400m14l03arg - Could not retrieve token from local cache. Please run 'az login'."}

PLAY RECAP *****************************************************************************************************************************************************************
localhost

Repro steps:
1.
1.
1.

### Lab

Lab 14a Ansible with Azure

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by omgitsjocke** [comment]
I had the very same problem. In another lab it was the "az cli" version 2.30 that caused issues, rolling back to 2.29 solved the problem there. It also solved the problem here, could get the machine deployed after doing this:

sudo apt-get install azure-cli=2.29.2-1~bionic
az login
az account get-access-token

Not sure if the get-access-token was required, that to my understanding should be used to work in 2.30. But it did not work for me on version 2.30

Info on the changes:
https://docs.microsoft.com/en-us/cli/azure/msal-based-azure-cli

**Comment by vnvbadri** [comment]
It worked thanks

**Comment by omgitsjocke** [comment]
I still think they should fix it to support "az cli" v2.30 though

**Comment by luisdanielse** [comment]
The problem persists. Thanks to omgitsjocke I was able to finish the lab 👍

**Comment by LuizMacedo** [comment]
The Ansible lab and content will be removed from AZ-400. I'm archiving the issue.
